# Generated by Django 3.2.2 on 2021-05-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'laptop'), ('TW', 'top Wear'), ('BW', 'Bottom wear')], max_length=5),
        ),
    ]
